### ISSUE TITLE
Unobvious server example

### ISSUE THREAD

**Issue by sem-hub** [rustls/hyper-rustls#154]
Could server.rs be extended to be clear how to handle errors here:
    // Prepare a long-running future stream to accept and serve clients.
    let incoming_tls_stream = stream! {
        loop {
            let (socket, _) = tcp.accept().await?;
            let stream = tls_acceptor.accept(socket).map_err(|e| {
                println!("[!] Voluntary server halt due to client-connection error...");
                // Errors could be handled here, instead of server aborting.
                // Ok(None)
                error(format!("TLS Error: {:?}", e))
            });
            yield stream.await;
        }
    };

It looks impossible to return Ok(None) from map_err().

**Comment by Parth** [comment]
Possible dupe: #113 

That thread seems to raise some larger concerns about the concurrency too

**Comment by djc** [comment]
Yeah, let's keep this discussion in #113.
