### ISSUE TITLE
Can't resolve IP address with square brakets

### ISSUE THREAD

**Issue by digitwolf** [rustls/hyper-rustls#181]
### Problem
Sending to destination like ```https://[::1]/``` fails with error ```invalid dnsname```.

Error is thrown here https://github.com/rustls/hyper-rustls/blob/main/src/connector.rs#L95

### Analysis
hyper-rustls resolves the Hostname as [```hyper::Uri::host``` ](https://docs.rs/hyper/latest/hyper/struct.Uri.html#method.host)
This makes hostname = "[::1]" which is HTTP-specific form of writing IPv6 address.

>Because IPv6 addresses contain colons, they cannot be directly used in URLs because the colons would conflict with both the protocol declaration (http:// or https://) and port numbers. Therefore, when a literal IPv6 address is used, it is encased in a bracket, like http://[2001:db8::1]:80
https://en.wikiversity.org/wiki/IPv6

### Root-Cause
hyper-rustls is resolving the host name using ```rustls::ServerName::try_from(hostname)``` which does not expect square brackets in IP because internally it uses 

### Proposed solution
Since square brakets are coming from hyper and not part standard IP notation I propose that we remove any square brakets inside of the connector before calling the ```rustls::ServerName::try_from(hostname)```

Will post a PR in bit

**Comment by djc** [comment]
Are you setting an actual DNS server name separately? Because rustls doesn't currently support IP addresses in certificates it won't otherwise be able to establish a session anyway.

**Comment by digitwolf** [comment]
I am not using a DNS, but I am using custom certs and all custom rustls cert verifiers. I have checked locally and this works.

**Comment by BiagioFesta** [comment]
> Because rustls doesn't currently support IP addresses in certificates

Shouldn't https://github.com/rustls/rustls/pull/1032 mitigate this?

I see this current `main` branch depends on `rustls 0.20.1` (so probably that PR is not in the code)

With that patch on rustls and a custom cert verifiers, it should be feasible if I am not wrong.

**Comment by djc** [comment]
I've submitted https://github.com/rustls/hyper-rustls/pull/183.
