### ISSUE TITLE
`HttpsConnectorBuilder::enable_all_versions` doesn't enable ALPN for http/1.1

### ISSUE THREAD

**Issue by mmalenic** [rustls/hyper-rustls#208]
When building a `HttpsConnectorBuilder` using `enable_all_versions`, ALPN does not seem to be enabled with `http/1.1`, and only `h2` is enabled:

https://github.com/rustls/hyper-rustls/blob/286e1fa57ff5cac99994fab355f91c3454d6d83d/src/connector/builder.rs#L183

However, calling `enable_http1` followed by `enable_http2` does enable ALPN for both versions.

This causes the client example to fail when using a `http/1.1` server, and a client built with `enable_all_versions`.

For example, with https://github.com/mmalenic/hyper-rustls/commit/863812f617c3b752ee4b32dcd13456be41053692, running the following:
```sh
cargo run --example server
```
```sh
cargo run --example client --features http2 "https://localhost:1337" examples/sample.pem
```
Results in the error:
```
FAILED: Could not get: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: AlertReceived(NoApplicationProtocol) } })
```
Is this the intended behaviour?

cc @norling @dbampalikis @brainstorm

**Comment by djc** [comment]
That seems like clearly a bug! Reading this code I forget how this was intended to work. IIRC the `enable_all_versions()` PR lay dormant for a pretty long while, so it's possible it got misrebased (and, appears to lack a test).

If one of you is able to submit a PR to fix (and, ideally add a test similar to the existing tests), I'd be happy to review and get a new release out!
