### ISSUE TITLE
Release TLSAcceptor

### ISSUE THREAD

**Issue by robinfriedli** [rustls/hyper-rustls#209]
I was following the server example and noticed that TLSAcceptor from #186 hasn't actually been released yet. I'm currently pulling the dependency off of GitHub instead of crates.io as an alternative but it would be great if you could publish a new release, provided there are no blocking issues.

**Comment by robinfriedli** [comment]
Also, slightly off topic, I was wondering how the TLSAcceptor (or TlsStream in general) handles invalid data in the request, does it log an error or terminate the hyper server?

**Comment by djc** [comment]
The `TlsAcceptor` type merely implements hyper's `Accept` trait -- it does not log errors but yields them to the caller. Review the hyper documentation to determine what hyper does when the `Accept` impl returns an error.
