### ISSUE TITLE
Hyper v1 compatibility

### ISSUE THREAD

**Issue by Colerar** [rustls/hyper-rustls#234]
Hyper v1 removed `hyper::Client` and move it to [hyper-util](https://crates.io/crates/hyper-util), called [client::legacy::Client](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/struct.Client.html).

What is the future of this crate? Is there any roadmap?

**Comment by djc** [comment]
Personally, getting a hyper-rustls out with hyper 1 is a fairly high priority for me. When I worked on it a bit over a week ago, however, there was no hyper-util library yet so porting hyper-rustls wasn't really feasible. I intend to take a look at the open PR and remaining issues soon.

**Comment by gngpp** [comment]
me too

**Comment by kurtbuilds** [comment]
Is there already a branch in progress to complete this?

I took a stab at this but got lost. The https://hyper.rs/guides/1/upgrading/ upgrade guide unfortunately doesn't discuss the internals that this library seems to touch (`Accept` and so on). I'd be happy to take another swing if I could get some guidance.

**Comment by Arnavion** [comment]
https://github.com/rustls/hyper-rustls/pull/232

**Comment by nicolaspernoud** [comment]
There seems to be a fork here : https://github.com/Gelbpunkt/hyper-rustls/tree/hyper-v1 ...

**Comment by gngpp** [comment]
> There seems to be a fork here : https://github.com/Gelbpunkt/hyper-rustls/tree/hyper-v1 ...这里似乎有一个分叉：https://github.com/Gelbpunkt/hyper-rustls/tree/hyper-v1......

good, have you tried it and does it work properly?

**Comment by nicolaspernoud** [comment]
no, not yet : it seems to be a work in progress.

**Comment by djc** [comment]
That's actually a PR against this project: https://github.com/rustls/hyper-rustls/pull/232. Looks like it should be merged and released soon.

**Comment by nicolaspernoud** [comment]
Good news ! Thanks !

**Comment by cpu** [comment]
[0.26.0](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.26.0) with Hyper 1.0 support has been published.

**Comment by gngpp** [comment]
good!
