### ISSUE TITLE
Release with rustls 0.22 support?

### ISSUE THREAD

**Issue by tusharmath** [rustls/hyper-rustls#247]
Thanks for this wonderful library! It makes our lives much easier 🙌

Can we please have a tiny release for hyper-rustls with the latest version of rusttls 🙏

**Comment by djc** [comment]
We've been waiting for hyper 1 support, see #234. But maybe we should do an intermediate release without that?

**Comment by tusharmath** [comment]
that'd be great! We can make another release with hyper 1. This way users who are not on hyper 1 can at least upgrade.

**Comment by Vagelis-Prokopiou** [comment]
Yes. I would vote for this too. Since the latest main is already updated and it is no extra work, I would also like such a release.
Thanks a lot and happy new year to everybody.

**Comment by ahl** [comment]
We would use this as well. Thanks!

**Comment by cpu** [comment]
A [0.25.0](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.25.0) release using Rustls 0.22 is now available. This release continues to use pre-1.0 Hyper, so we'll follow up with another major version release in the future once we've updated to Hyper 1.0.

Thanks!
