### ISSUE TITLE
Release 0.25.0 without hyper 1 support?

### ISSUE THREAD

**Issue by Lo236816** [rustls/hyper-rustls#248]
We've been waiting for hyper 1 support, see #234. But maybe we should do an intermediate release without that?

_Originally posted by @djc in https://github.com/rustls/hyper-rustls/issues/247#issuecomment-1871835775_

**Comment by djc** [comment]
Let's keep this discussion in #247 -- I don't think discussing this in a separate issue is particularly helpful.
