### ISSUE TITLE
Prepare v0.25 release, update to Rustls v0.22 

### ISSUE THREAD

**Issue by cpu** [rustls/hyper-rustls#249]
This issue collects up preparation work for a hyper-rustls 0.25 release, bringing in the update to Rustls 0.22

Since `main` has already had its `Cargo.toml` version updated this is an issue instead of a pull-request.

Resolves https://github.com/rustls/hyper-rustls/issues/247

## Proposed Changelog

* The Rustls dependency has been updated to 0.22
* The `acceptor` module is now public.
* The `TlsStream` type now has `io` and `connection` accessor methods for getting a reference to the underlying I/O stream and `rustls::ServerConnection`.
* A new `AcceptorBuilder::with_connector` method is added for taking a generic acceptor implementing `Accept`.
* `ConnectorBuilder::enable_all_versions` has been fixed to advertise the correct ALPN values based on enabled crate features.
* `ConnectorBuilder::with_native_roots` has been updated to be fallible, allowing a failure to load native roots to be handled by the caller instead of producing a panic.

**Comment by cpu** [comment]
@djc @ctz Would you folks mind +1ing the proposed changelog in comments here? There wasn't a code change to merit a pull request but it makes the "approval" of this proposed release a little awkward :-)

**Comment by ctz** [comment]
Looks complete to me!

**Comment by djc** [comment]
> * The `Acceptor` module is now public and has `io` and `connection` accessors fns for getting a reference to the underlying I/O stream and `rustls::ServerConnection`.

I find "The `Acceptor` module" confusing, since that doesn't look like a module name? And you didn't link the PR here and I'm too lazy to dig up the PR right now. Also "accessors fns" I would probably write as "accessor functions" or "accessor methods" maybe. Maybe the rustls dependency update should move to the top of the list?

👍 modulo these nits.

**Comment by cpu** [comment]
> I find "The Acceptor module" confusing, since that doesn't look like a module name?

Good catch, that should be `acceptor` not `Acceptor`. Fixed.

>  And you didn't link the PR here and I'm too lazy to dig up the PR right now.

That one is https://github.com/rustls/hyper-rustls/pull/219 The PRs will be linked from the GitHub generated changelog for the final release notes so I didn't source them for the proposed text.

>  Also "accessors fns" I would probably write as "accessor functions" or "accessor methods" maybe.

I split this out into a line about the `acceptor` module being public, and a separate line about `TlsStream` getting the new accesor methods.

> Maybe the rustls dependency update should move to the top of the list?

Done.

Thanks for the review :+1:

**Comment by cpu** [comment]
* Pushed a [v0.25.0 tag](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.25.0)
* Published hyper-rustls v0.25.0 at registry `crates-io`
* Created a [0.25.0 GitHub release](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.25.0)
