### ISSUE TITLE
Prepare v0.26 release, update to Hyper 1.0

### ISSUE THREAD

**Issue by cpu** [rustls/hyper-rustls#250]
This issue collects up preparation work for a hyper-rustls 0.26 release, bringing in the update to Hyper 1.0

Since main has already had its Cargo.toml version updated this is an issue instead of a pull-request.

Resolves https://github.com/rustls/hyper-rustls/issues/234

## Proposed Release Notes

* The `hyper` crate dependency has been updated to 1.0. `hyper-rustls` now uses the new `hyper-util` crate to replace functionality removed from `hyper`.
* The `Acceptor` API has been removed and relevant examples updated. Hyper 1.0 has library consumers handle binding sockets and accepting connections themselves, removing the need for the `Acceptor` API. See `examples/server.rs` for an up to date example for accepting connections.
* The `tokio-runtime` feature has been removed - `hyper-rustls` depends on `hyper-util`, and the `tokio` feature in hyper-util is required for the necessary IO adapter traits. Tokio was already a hard dependency of this crate.

**Comment by cpu** [comment]
@djc @ctz @Gelbpunkt Do these proposed release notes look good to you? I can publish a release once there are +1`'s for the proposed notes.

**Comment by Gelbpunkt** [comment]
The release notes look good to me!

**Comment by ctz** [comment]
Looks good to me too!

**Comment by devsnek** [comment]
@cpu fyi looking at recent signed commits it seems your gpg keys might need to be updated

**Comment by Gelbpunkt** [comment]
> @cpu fyi looking at recent signed commits it seems your gpg keys might need to be updated

I think the "Unverified" is because I require commits authored by me to be signed with my key and even though I sign them on my branches, the signature is lost when using "squash and rebase" in the Github merge options. No key has expired.

**Comment by cpu** [comment]
I'm seeing my signature subkey showing an expiry of 2024-03-10. I concur with @Gelbpunkt that this is an artifact of merge commits and GitHub's UI. I regularly see my commits showing as "unverified" when merged by others so I've disabled vigilant mode in my account settings. I don't really believe its a useful practice with the current state of GitHub.

**Comment by djc** [comment]
LGTM.

**Comment by cpu** [comment]
* Pushed a [v/0.26.0 tag](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.26.0)
* Published hyper-rustls v0.26.0 at registry `crates-io`
* Created [a GitHub release](https://github.com/rustls/hyper-rustls/releases/tag/v%2F0.26.0)
