### ISSUE TITLE
Rust minimum version should be updated

### ISSUE THREAD

**Issue by hhartzer** [rustls/hyper-rustls#258]
Hi,

It looks like some new Rust features are being used, causing the build to fail for me in a less than intuitive way. 1.74 is too old, so I assume 1.75 or 1.76 is the minimum version. I know little of Rust, but I think this is easy to set in Cargo.toml, and currently is but to something much older.

Thanks!

Related: https://github.com/astral-sh/uv/issues/2442

**Comment by cpu** [comment]
Hi there, 

This crates minimum supported rust version is 1.64 (https://github.com/rustls/hyper-rustls/blob/main/Cargo.toml#L5) so your Rust version should be OK.

We test this Rust version in our CI as well: https://github.com/rustls/hyper-rustls/blob/main/.github%2Fworkflows%2Fbuild.yml#L83-L97

Are you sure the compilation error you are getting with uv is from this crate? The error in your linked issue looks to me to be from a crate named 'pubgrub':

>  error[E0562]: `impl Trait` only allowed in function and inherent method return types, not in trait method return types
>         --> /root/.cargo/git/checkouts/pubgrub-4eebf9758cb3b340/addbaf1/src/solver.rs:264:30

**Comment by hhartzer** [comment]
Aw, my bad. I think you are right! Thank you for setting me on the right path.

It looks like the installation is multi-threaded or something, so the order wasn't what I was expecting.

**Comment by cpu** [comment]
Happy to help :-) Cargo installs dependencies in parallel by default and it's easy to mix up the output.
