### ISSUE TITLE
0.23.2 of rusttls

### ISSUE THREAD

**Issue by Lewiscowles1986** [rustls/hyper-rustls#262]
Hello, thank you for your time authoring this library and reading this

I Have an open PR which explains my end-goal https://github.com/rustls/rustls-platform-verifier/pull/76 I figured I'd raise an issue here as I can't raise a PR until that PR is complete, as this repo seems to depend on that. `rustls` not being a monorepo prevents me who only has passing affinity with rust, from moving multiple things at once.

The north star of this work is to allow me to attempt to fix-up https://github.com/awslabs/llrt/pull/280 which relies on something else, which relies on this package.

I would also like to ask if a release could be created after this work is complete so that others using rustls can use with 0.23.2 of the core library.

**Comment by djc** [comment]
This is waiting for the tokio-rustls release, but rest assured that we are on it.

https://github.com/rustls/tokio-rustls/pull/59

**Comment by FemLolStudio** [comment]
> This is waiting for the tokio-rustls release, but rest assured that we are on it.

As I see it got merget and released.

**Comment by djc** [comment]
See work in progress in #263.
