### ISSUE TITLE
Expose feature flag to enable FIPS compliant build of AWS-LC.

### ISSUE THREAD

**Issue by tobz** [rustls/hyper-rustls#267]
It looks like the 0.27.0 release pulled in the necessary upstream crate bumps so that AWS-LC can be used as the `rustls` backend, and with a high enough version to also use the FIPS-compliant build... 🎉 . However, users still need to do the add-your-own-dependency-to-set-the-feature-flag-you-want hack if they're using `hyper-rustls` and want to use that FIPS-compliant mode.

I plan to whip up a quick PR to expose that, but wanted to file the issue so I don't forget. 😂

**Comment by djc** [comment]
Thanks for reporting -- happy to review a PR for this!
