### ISSUE TITLE
Latest version (0.27.1) fails to build for `docs.rs`

### ISSUE THREAD

**Issue by tobz** [rustls/hyper-rustls#272]
As seen here: https://docs.rs/crate/hyper-rustls/0.27.1/builds/1185949

This looks to be directly related to my changes in #268, and I'm going to try and take a look at it today.

**Comment by cpu** [comment]
d'oh! Thanks for noticing & filing an issue.

We ran into this in the rustls repo as well: https://github.com/rustls/rustls/pull/1827 I think the same fix is probably what we need here.

**Comment by tobz** [comment]
Ah neat! I'll try and take a look at that later and apply it here.
