### ISSUE TITLE
hyper-rustls fails on windows machines

### ISSUE THREAD

**Issue by opensource-inemar-net** [rustls/hyper-rustls#280]
compilation of hyper-rustls fails on windows machines due to rustls using now AWS-LC-SYS as a default crypto provider.
AWS-LC-SYS needs additional build dependencies which are normally not present on windows machines

error: failed to run custom build command for `aws-lc-sys v0.20.0`

Caused by:
  process didn't exit successfully: `C:\aPerf\dioxus\test1\target\debug\build\aws-lc-sys-04a602ea992483f7\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC

  --- stderr
  AWS_LC_SYS_NO_ASM=1
  AWS_LC_SYS_CMAKE_BUILDER=1
  Missing dependency: cmake
  thread 'main' panicked at C:\Users\yyyyyy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\aws-lc-sys-0.20.0\builder/main.rs:289:38:
  called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

To reproduce on a windows machine. 

cargo init
cargo add hyper-rustls
cargo build

This is discussed at:
https://github.com/aws/aws-lc/issues/1477
and 
https://github.com/rustls/rustls/issues/1913

and causes also upstream problems
https://github.com/Azure/azure-sdk-for-rust/issues/1677

Recommendation is to deactivate rustls default feature and make AWS-LC-SYS opt in

**Comment by ctz** [comment]
> Recommendation is to deactivate rustls default feature and make AWS-LC-SYS opt in

This crate reexports the relevant crate features, so downstream crates can (and should) do precisely this, such that the choice of provider is left to the "topmost" crate.

**Comment by opensource-inemar-net** [comment]
the problem is that the default setting should be on the safe side and features additive.
The higher up in the stack the more difficult and brittle becomes, because on of the intermediate layer might forget to expose the necessary config options.

But you have more experience therefore it is your decision.

Close it or keep it open as you prefer

**Comment by djc** [comment]
Since you already linked to the relevant discussion in rustls, I don't think it makes sense to keep this open as a separate issue since this crate should match rustls' defaults. If you have any new arguments to contribute, please do so in the rustls issue.
