### ISSUE TITLE
Missing support for ipv4/ipv6 subjects

### ISSUE THREAD

**Issue by kpcyrd** [rustls/hyper-rustls#56]
I've tried to send a request to `https://1.1.1.1`. This fails with an error:
```
StringError("invalid dnsname")
```

The error seems to be coming from hyper-rustls, the https-connector I use:
https://github.com/ctz/hyper-rustls/blob/276c10aa7373d3c8da7d39d22b82f7a4600f6bd2/src/connector.rs#L81

**Comment by lucab** [comment]
Indeed, only `DNSName` are supported (thus, no ipv4/ipv6 subject matching).

This is a rustls limitation which in turn comes from webpki:
 * https://github.com/ctz/rustls/issues/184
 * https://github.com/briansmith/webpki/issues/54

**Comment by cpu** [comment]
This will be resolved by https://github.com/rustls/hyper-rustls/pull/199

**Comment by cpu** [comment]
hyper-rustls 0.24.0 was released with this support.
