### ISSUE TITLE
FAILED: error accepting connection: unexpected end of file

### ISSUE THREAD

**Issue by IThawk** [rustls/hyper-rustls#82]
Finished dev [unoptimized + debuginfo] target(s) in 6.47s
     Running `target\debug\web_tcp.exe`
Starting to serve on https://127.0.0.1:1337.
[!] Voluntary server halt due to client-connection error...
FAILED: error accepting connection: unexpected end of file
error: process didn't exit successfully: `target\debug\web_tcp.exe` (exit code: 1)

**Comment by cpu** [comment]
I don't believe the `web_tcp.exe` binary is part of the project anymore. I'm going to close this issue but if you're still facing problems running the latest version of the crate on Windows please reply with additional reproduction information. Thanks!
